/**
 * 🔧 SOLUTION URGENTE 404 - CONTOURNEMENT IMMÉDIAT
 * Correction temporaire en attendant le redéploiement
 */

console.log('🚨 CONTOURNEMENT URGENT 404')
console.log('='.repeat(40))
console.log('')

console.log('⚠️ PROBLÈME IDENTIFIÉ:')
console.log('Nouvelle route /mes-projets pas encore déployée sur Render')
console.log('→ Cause: Commit récent pas encore activé sur backend')
console.log('')

console.log('🔧 SOLUTION TEMPORAIRE:')
console.log('Utiliser routes existantes qui fonctionnent')
console.log('')

console.log('🧪 TESTS IMMÉDIATS:')
console.log('(Exécuter dans https://jig-projet-ea3m.vercel.app → F12 Console)')
console.log('')

console.log('// ============ TEST 1: AUTO-APPROVE (TOUJOURS OK) ============')
console.log('console.log("🚀 Auto-approbation des projets...");')
console.log('fetch("https://jig-projet-1.onrender.com/api/projets/auto-approve-all", {')
console.log('  method: "POST"')
console.log('})')
console.log('.then(r => r.json())')
console.log('.then(data => {')
console.log('  console.log("✅ Auto-approve résultat:", data);')
console.log('  if(data.count > 0) {')
console.log('    console.log("🎉 Projets approuvés! Vote maintenant possible.");')
console.log('  }')
console.log('});')
console.log('')

console.log('// ============ TEST 2: PROJETS PUBLIC (VOTE) ============')
console.log('setTimeout(() => {')
console.log('  console.log("🗳️ Test projets pour vote...");')
console.log('  fetch("https://jig-projet-1.onrender.com/api/projets/public")')
console.log('    .then(r => r.json())')
console.log('    .then(data => {')
console.log('      console.log("📊 Projets publics:", data.data?.length || 0);')
console.log('      if(data.data?.length > 0) {')
console.log('        console.log("✅ Vote fonctionne - projets visibles");')
console.log('        const projetPAO = data.data.find(p => p.categorie === "PAO");')
console.log('        if(projetPAO) {')
console.log('          console.log("🎯 Projet PAO trouvé:", projetPAO.titre);')
console.log('        }')
console.log('      }')
console.log('    });')
console.log('}, 2000);')
console.log('')

console.log('// ============ TEST 3: MES-PROJETS VIA ROUTE LEGACY ============')
console.log('setTimeout(() => {')
console.log('  console.log("📋 Test mes-projets via route backup...");')
console.log('  ')
console.log('  // Se connecter d\'abord si pas connecté')
console.log('  const token = localStorage.getItem("token") || localStorage.getItem("jig2026_token");')
console.log('  ')
console.log('  if(!token) {')
console.log('    console.log("🔐 Connexion tianakone00@gmail.com...");')
console.log('    fetch("https://jig-projet-1.onrender.com/api/auth/login", {')
console.log('      method: "POST",')
console.log('      headers: { "Content-Type": "application/json" },')
console.log('      body: JSON.stringify({')
console.log('        "email": "tianakone00@gmail.com",')
console.log('        "motDePasse": "VotrePasse" // REMPLACER')
console.log('      })')
console.log('    })')
console.log('    .then(r => r.json())')
console.log('    .then(data => {')
console.log('      if(data.token) {')
console.log('        localStorage.setItem("token", data.token);')
console.log('        localStorage.setItem("user", JSON.stringify(data.user));')
console.log('        console.log("✅ Connecté:", data.user.nom);')
console.log('        testMesProjets(data.user.id, data.token);')
console.log('      }')
console.log('    });')
console.log('  } else {')
console.log('    const user = JSON.parse(localStorage.getItem("user") || "{}");')
console.log('    testMesProjets(user.id, token);')
console.log('  }')
console.log('  ')
console.log('  function testMesProjets(userId, token) {')
console.log('    console.log("📋 Test mes-projets pour user:", userId);')
console.log('    ')
console.log('    // Tester nouvelle route d\'abord')
console.log('    fetch("https://jig-projet-1.onrender.com/api/projets/mes-projets", {')
console.log('      headers: { "Authorization": "Bearer " + token }')
console.log('    })')
console.log('    .then(r => {')
console.log('      if(r.status === 404) {')
console.log('        console.log("❌ Nouvelle route pas déployée, utilisation legacy...");')
console.log('        return fetch(`https://jig-projet-1.onrender.com/api/projets/user/${userId}`, {')
console.log('          headers: { "Authorization": "Bearer " + token }')
console.log('        });')
console.log('      }')
console.log('      return r;')
console.log('    })')
console.log('    .then(r => r.json())')
console.log('    .then(data => {')
console.log('      console.log("📋 Mes projets result:", data);')
console.log('      if(data.data?.length > 0) {')
console.log('        console.log(`✅ ${data.data.length} projet(s) trouvé(s)`);')
console.log('        console.log("🎯 Projet PAO visible:", data.data.find(p => p.categorie === "PAO")?.titre);')
console.log('      } else {')
console.log('        console.log("⚠️ Aucun projet - vérifiez auto-approve");')
console.log('      }')
console.log('    })')
console.log('    .catch(e => console.log("❌ Erreur mes-projets:", e.message));')
console.log('  }')
console.log('}, 4000);')
console.log('')

console.log('🎯 INSTRUCTIONS RAPIDES:')
console.log('')
console.log('1. 🌐 https://jig-projet-ea3m.vercel.app → F12 Console')
console.log('2. 📋 Copier TOUT le code ci-dessus')
console.log('3. ✏️ Remplacer "VotrePasse" par votre mot de passe réel')
console.log('4. ▶️ Appuyer Entrée pour exécuter')
console.log('5. ⏱️ Attendre 10 secondes - tout se teste automatiquement')
console.log('')

console.log('📊 RÉSULTATS ATTENDUS:')
console.log('✅ Auto-approve: X projets approuvés')
console.log('✅ Projets public: Projets visibles sur /vote')
console.log('✅ Mes-projets: Votre projet PAO visible')
console.log('')

console.log('🔄 SI TOUJOURS 404:')
console.log('• Backend Render en cours de réveil (attendre 30s)')
console.log('• Nouvelle route pas encore déployée (normal)')
console.log('• Script utilise routes backup automatiquement')
console.log('')

console.log('🎉 APRÈS SUCCÈS:')
console.log('📱 https://jig-projet-ea3m.vercel.app/voter')
console.log('📋 https://jig-projet-ea3m.vercel.app/mes-projets')
console.log('📊 https://jig-projet-ea3m.vercel.app/mes-suivis')
console.log('')

console.log('✨ SOLUTION IMMÉDIATE PRÊTE!')